(defun run-tests ()
  (progn 
         (format t "Loading tests and functions...")
         (cd "~/Documents/personal/university-of-minnesota/csci-5511-artificial-intelligence/csci-5511")
         (load "test-all.lisp")
         (load "functionatom.lisp")
         (load "replaceword.lisp")
         (format t "Loading completed.  Invoking all tests...")
         (test-all)
  )
)
