(defun test-queens-generate-child-states()
   (format t "Initiating tests for ~S...~%" #'queens-generate-child-states)
   (tf:error-if-failed1 '((0 0) (1 1) (2 2) (3 3)) '(((0 1) (1 1) (2 2) (3 3))
                                                     ((1 0) (1 1) (2 2) (3 3))
                                                     ((1 0) (0 0) (2 2) (3 3))
                                                     ((0 1) (0 0) (2 2) (3 3))
                                                     ((0 2) (0 0) (2 2) (3 3))
                                                     ((1 2) (0 0) (2 2) (3 3))
                                                     ((2 1) (0 0) (2 2) (3 3))
                                                     ((2 0) (0 0) (2 2) (3 3))
                                                     ((2 1) (0 0) (1 1) (3 3))
                                                     ((1 2) (0 0) (1 1) (3 3))
                                                     ((1 3) (0 0) (1 1) (3 3))
                                                     ((2 3) (0 0) (1 1) (3 3))
                                                     ((3 2) (0 0) (1 1) (3 3))
                                                     ((3 1) (0 0) (1 1) (3 3))
                                                     ((3 2) (0 0) (1 1) (2 2))
                                                     ((2 3) (0 0) (1 1) (2 2)))  #'queens-generate-child-states)
   (format t "~&All ~S tests completed.~%" #'queens-generate-child-states)
)


(defun test-queens-heuristic()
   (format t "Initiating tests for ~S...~%" #'queens-heuristic)
   (tf:error-if-failed1 '((0 0) (1 1) (2 2) (3 3)) 12  #'queens-heuristic)
   (tf:error-if-failed1 '((0 2) (1 0) (2 3) (3 1)) 0  #'queens-heuristic)
   (tf:error-if-failed1 '((1 0) (2 0) (0 2) (3 3)) 4  #'queens-heuristic)
   (tf:error-if-failed1 '((1 0) (2 1) (0 2) (3 3)) 2  #'queens-heuristic)
   (format t "~&All ~S tests completed.~%" #'queens-heuristic)
)


;;; Run all a-star tests.
(defun test-all-queens()
   (test-queens-generate-child-states)
   (test-queens-heuristic)
)
